# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd44772eae027159dde329645e854b9157f314150b141dc51c96a3528e46d8b98eadb81a3bfbca48265851e1b9d4348e9b68cf0e2e6149f88fa12048fae06300

test:
  secret_key_base: 2ae128b85a7cb01b7ba8e3df10cdd29827f113553009880e297c83c005e99d80d1f8d577774ab834e31beda6a5488c959e4ce8cd949e8473262dea82b90f518b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
